jobs:
  superlint:
    name: Super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Deps
        run: for i in $(ls -d */); do pushd $i; yarn; popd; done
      - env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: ./backend*/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_ES_CONFIG_FILE: .eslint-backend.json
          LINTER_RULES_PATH: .github/linters
          TYPESCRIPT_ES_CONFIG_FILE: .eslint-backend.json
          VALIDATE_CSS: false
          VALIDATE_JSON: false
          VALIDATE_TYPESCRIPT_STANDARD: false
        name: Lint BackEnd
        uses: github/super-linter/slim@v4
      - env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: ./beconnect-react-app/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_ES_CONFIG_FILE: .eslint-frontend.json
          LINTER_RULES_PATH: .github/linters
          TYPESCRIPT_ES_CONFIG_FILE: .eslint-frontend.json
          VALIDATE_CSS: false
          VALIDATE_JSON: false
          VALIDATE_TYPESCRIPT_STANDARD: false
        name: Lint Front End
        uses: github/super-linter/slim@v4
name: Linters
'on':
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
